server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: rental
          uri: http://localhost:8081
          predicates:
            - Path=/rentals/** 
        - id: system
          uri: http://localhost:8082
          predicates:
            - Path=/reserves/**,/returns/**
        - id: book
          uri: http://localhost:8083
          predicates:
            - Path=/books/** 
        - id: mypage
          uri: http://localhost:8084
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rental
          uri: http://rental:8080
          predicates:
            - Path=/rentals/** 
        - id: system
          uri: http://system:8080
          predicates:
            - Path=/reserves/**,/returns/**
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/books/** 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
