apiVersion: apps/v1
kind: Deployment
metadata:
  name: system
  labels:
    app: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
        - name: system
          image: username/system:latest
          ports:
            - containerPort: 8080
          env:
            - name: STATUS
              valueFrom:
                configMapKeyRef:
                  name: systemword
                  key: word
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5